# Generated by Django 5.2.2 on 2025-06-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iprocess',
            name='allocatedsize',
        ),
        migrations.RemoveField(
            model_name='iprocess',
            name='database',
        ),
        migrations.RemoveField(
            model_name='iprocess',
            name='name',
        ),
        migrations.RemoveField(
            model_name='iprocess',
            name='realsize',
        ),
        migrations.RemoveField(
            model_name='iprocess',
            name='tablename',
        ),
        migrations.AddField(
            model_name='iprocess',
            name='currentDevice',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='iprocess',
            name='jobNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='iprocess',
            name='osUserName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='iprocess',
            name='pid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='iprocess',
            name='routine',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='iprocess',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='iprocess',
            name='userName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
