# Generated by Django 5.2.2 on 2025-06-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_remove_iprocess_allocatedsize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iprocess',
            name='id',
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='currentDevice',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='jobNumber',
            field=models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='osUserName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='pid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='routine',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='userName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
