# Generated by Django 5.2.2 on 2025-06-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_remove_iprocess_id_alter_iprocess_currentdevice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprocess',
            name='currentDevice',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='osUserName',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='pid',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='routine',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='userName',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
