# Generated by Django 5.2.2 on 2025-06-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_alter_iprocess_currentdevice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprocess',
            name='currentDevice',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='jobNumber',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='osUserName',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='pid',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='routine',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='state',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iprocess',
            name='userName',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
